server:
  port: 8091

dubbo:
  registry:
    address: 127.0.0.1:2181
  port: 20880
  threadpool:
    size: 100
  timeout: 30000

##alipay
alipay:
  charset: UTF-8
  appid: 2018080860949446
  appprivatekey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCVGOnGbrNPxFc7tjp8o/1moZhwhK16Dwz9pDRmo1h/cXhCfL3Ax2d7SbQpwj1zbpNDRtNlDUr2m4oix18gjsvnZ0QGb8rc9CdTL6HIL5lAce0rrMc2ygWW6hvY0v6dAzXtHq3kNF/RwVqnYZevsk7uo4lePa3fYe1fFQKEHkSUOHQm5zEp8+rurQEBl5wxqZKCYA6r7vzrHc94kx0/74EPwSPIwa/gakjWaq3NuiCycYQrZLGlJrkdBfW+i/MUEjts9ufQ2SG0BfRho/iJa0xw6eLRobjTsy7lZE/lDwUDUjgHYVmSSpk4VX5inI7FigDKXiuuok0OrvOXUVKqws1jAgMBAAECggEAFBjxmh/d58itgY0EwTxRsf3iUHhx8dwJgj8aGSO3kCY5cazi3xOB7Wp38JEQO3kSPKVVZW+vRSKeMiXxuq/E6IJQ9xUmoTX//wSSqCtSWw+ASrzVdZsxubAA5O88Buoh4L6b7gDpUZrgn2NWUQaWATDmGV/zCgNnPcPVPP3ffKMSjiGF7oQhUoqehXTCVGJIxBrNqrBp7ikFSLzJYm8ElMNRsUAy9FoloSM6VEMtixUfm86kLwRbnXJd8YC1KF4yq8EUBUxgCYZnIbYKjybyWW4iZSGWiDY3720xXyOITGxrLOabVyl/xZz+wvAubxRSR0LJXFxCq65slymhKzujsQKBgQDWmPgJcV3p6lRHE+DMYdqEP6nM4ck1p5pRbrmtlxzck9W5WaQK6iRVxjwJ95mWY5XumYikm3GImaWDxGfkhTbA7K5VsU6pmNOffeb1LRv7J1DrgBQBlLcvOqU1x9bDFH9ydJnn+J+oOgCGZKPG7tDOgM7ZI4o+9Jy1IA/JtDmo5QKBgQCx3N7d/1nKV92XyghsNPxJmSO+/k6tvuDg6/Dn1CnlzxeRBHn3IVyrY9k5uvWKiEZSmfdoRga3yuW1RR6W9bF8pZ2Z/pv94D2dRpSb0C6V9OgzGCz+bJNSjpquazRy2cOKXDBmA/Asir3clHYLupeKoJTtJEmjHP7R+wu9kFUgpwKBgQCRIU7OBA+BfOqWT0k+sAb6XZvWZfSQBtOEsx972LC6NHjcK1WX1BXStIgyLXN/k8X4YXlZ6Y501YRsgs3IbJdFDkwwxALxC9xDBwDFW0aLKmG9gxcEorDojf7hSk9iC2DN5TGZAjnnqaJlQXbJuQUaQ16g1zpNrVy12gMTZIGCSQKBgQCLSBQ6sjElVCNSL0LjQabjF4o3kbwZMSW23OzdDnb04HRq+p9sGHMSP/Gm1LJdlpPDMZDd1iCCot+5UPRAcQxZOPQu2IRdjdGSLOhJEAC7K3r+MAtj/bBscQHOXmNHISKQYdsAuErHBqrhZlz+mFL9mvykq8sCcb1WwAoUm0cedwKBgQCyhaL7nFmk2VNJHeirxle5Fy3wo45n9P5uzyWeoxLGjToGAfr3nHRU++mHSHsaptBS8K0rafd218B10vQnlgb85pSzGD5wg/FhJY6pgGwASa64Zsk7+1u9oZyX3/nzLVZknT7qUp0jV/zJq0ZjH2urN++5ct70xLWjcFH33Ti9NA==
  publickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAku+he8ev3LM/q3yrDFZtcL7ZHThxgS1DXcygaWG8TmzPaKlyTwqqma0l1w6cFEfLkiKQMzt6S0TGeb/omBDFdx87FyB0JbPMRqRVtiiDZD8iSAI009JsORjfkT+k/lDo9LJ8BHc5cHHYZDKKs+2pcKRMXIeMy2npV2KCTpuFC5NTDIG4dlLWloaNzQB7/XVoIndVGUtDwhe0YNs4RDbh4IhEMhpBVR6VwVd8Xt1GBZ49TG0JUITmvNkTT08o/CptBEb1jxyYqQvd5Ole1xLJFcoBlzN0We+QC0RXN9dIb3s105/VW4AbAP3xu0rahkhYPPQZ6U+xnEQZYdbGh6f96QIDAQAB
  notifyurl: http://testpay.ilonw.com/alipay/notify
  gateway: https://openapi.alipay.com/gateway.do

##wechatpay
wechatpay:
  appId: wxa943123e5c3112db
  secretkey: 30769af26a3fba1132973aac74520fad
  mchId: 1509822911
  mchKey: XW6AW02G76LDZABZVYVHWBWD9MIXF5ZB
  notifyUrl: http://testpay.ilonw.com/wechatpay/notify
  withdraw: https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers
